# New ports collection makefile for:    clens
# Date created:         March 5, 2012
# Whom:                 Dale Rahn <drahn@conformal.com>
#
# $FreeBSD$
# 

PORTNAME=       clens
PORTVERSION=    0.4.0
CATEGORIES=     devel
MASTER_SITES=   https://opensource.conformal.com/snapshots/clens/ \
                LOCAL/bf

MAINTAINER=     None
COMMENT=        Convenience library to aid in porting OpenBSD code to other OSes

LICENSE=        ISCL
LICENSE_COMB=   single

.include <bsd.port.mk>
